train:
  data_object:
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.ReplicationPad
        target_seconds: 5.0
        sample_rate: 16000
      - _target_: src.transforms.LogPowerSpectrogram
        n_fft: 1724
        hop_length: 130
        power: 2.0
        eps: 1e-10
inference:
  data_object:
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.ReplicationPad
        target_seconds: 5.0
        sample_rate: 16000
      - _target_: src.transforms.LogPowerSpectrogram
        n_fft: 1724
        hop_length: 130
        power: 2.0
        eps: 1e-10
